
import { University, Product, User } from './types';

export const mockUser: User = {
  id: 101,
  name: 'Ada from Unilag',
  email: 'ada@unilag.com',
  universityName: 'University of Lagos, Akoka',
};

export const mockUsers: User[] = [mockUser];

export const universities: University[] = [
    // Federal Universities
    { name: "Abubakar Tafawa Balewa University, Bauchi", type: "Federal" },
    { name: "Ahmadu Bello University, Zaria", type: "Federal" },
    { name: "Air Force Institute of Technology, Kaduna", type: "Federal" },
    { name: "Alex Ekwueme Federal University, Ndufu-Alike, Ebonyi State", type: "Federal" },
    { name: "Bayero University, Kano", type: "Federal" },
    { name: "Federal University, Gashua, Yobe", type: "Federal" },
    { name: "Federal University, Gusau, Zamfara", type: "Federal" },
    { name: "Federal University, Birnin Kebbi", type: "Federal" },
    { name: "Federal University, Dutse, Jigawa State", type: "Federal" },
    { name: "Federal University, Dutsin-Ma, Katsina", type: "Federal" },
    { name: "Federal University, Kashere, Gombe State", type: "Federal" },
    { name: "Federal University, Lafia, Nasarawa State", type: "Federal" },
    { name: "Federal University, Lokoja, Kogi State", type: "Federal" },
    { name: "Federal University, Otuoke, Bayelsa", type: "Federal" },
    { name: "Federal University, Oye-Ekiti, Ekiti State", type: "Federal" },
    { name: "Federal University, Wukari, Taraba State", type: "Federal" },
    { name: "Federal University of Agriculture, Abeokuta, Ogun State", type: "Federal" },
    { name: "Federal University of Agriculture, Makurdi, Benue State", type: "Federal" },
    { name: "Federal University of Agriculture, Zuru, Kebbi State", type: "Federal" },
    { name: "Federal University of Health Sciences, Azare, Bauchi State", type: "Federal" },
    { name: "Federal University of Health Sciences, Ila Orangun, Osun State", type: "Federal" },
    { name: "Federal University of Petroleum Resources, Effurun, Delta State", type: "Federal" },
    { name: "Federal University of Technology, Akure, Ondo State", type: "Federal" },
    { name: "Federal University of Technology, Babura, Jigawa State", type: "Federal" },
    { name: "Federal University of Technology, Ikot Abasi, Akwa Ibom State", type: "Federal" },
    { name: "Federal University of Technology, Minna, Niger State", type: "Federal" },
    { name: "Federal University of Technology, Owerri, Imo State", type: "Federal" },
    { name: "Michael Okpara University of Agricultural, Umudike, Abia State", type: "Federal" },
    { name: "Modibbo Adama University of Technology, Yola, Adamawa State", type: "Federal" },
    { name: "National Open University of Nigeria, Lagos", type: "Federal" },
    { name: "Nigerian Defence Academy, Kaduna", type: "Federal" },
    { name: "Nigerian Maritime University, Okerenkoko, Delta State", type: "Federal" },
    { name: "Nnamdi Azikiwe University, Awka, Anambra State", type: "Federal" },
    { name: "Obafemi Awolowo University, Ile-Ife, Osun State", type: "Federal" },
    { name: "Police Academy, Wudil, Kano State", type: "Federal" },
    { name: "University of Abuja, Gwagwalada, Abuja", type: "Federal" },
    { name: "University of Agriculture and Environmental Sciences, Umuagwo, Imo State", type: "Federal" },
    { name: "University of Benin, Benin City, Edo State", type: "Federal" },
    { name: "University of Calabar, Calabar, Cross River State", type: "Federal" },
    { name: "University of Ibadan, Ibadan, Oyo State", type: "Federal" },
    { name: "University of Ilorin, Ilorin, Kwara State", type: "Federal" },
    { name: "University of Jos, Jos, Plateau State", type: "Federal" },
    { name: "University of Lagos, Akoka, Lagos State", type: "Federal" },
    { name: "University of Maiduguri, Maiduguri, Borno State", type: "Federal" },
    { name: "University of Nigeria, Nsukka, Enugu State", type: "Federal" },
    { name: "University of Port Harcourt, Port Harcourt, Rivers State", type: "Federal" },
    { name: "University of Uyo, Uyo, Akwa Ibom State", type: "Federal" },
    // State Universities
    { name: "Abia State University, Uturu", type: "State" },
    { name: "Adamawa State University, Mubi", type: "State" },
    { name: "Adekunle Ajasin University, Akungba-Akoko, Ondo State", type: "State" },
    { name: "Akwa Ibom State University, Ikot Akpaden", type: "State" },
    { name: "Ambrose Alli University, Ekpoma, Edo State", type: "State" },
    { name: "Bauchi State University, Gadau", type: "State" },
    { name: "Bayelsa Medical University, Yenagoa", type: "State" },
    { name: "Benue State University, Makurdi", type: "State" },
    { name: "Borno State University, Maiduguri", type: "State" },
    { name: "Chukwuemeka Odumegwu Ojukwu University, Anambra State", type: "State" },
    { name: "Cross River State University of Science & Technology, Calabar", type: "State" },
    { name: "Delta State University, Abraka", type: "State" },
    { name: "Ebonyi State University, Abakaliki", type: "State" },
    { name: "Edo State University, Uzairue", type: "State" },
    { name: "Ekiti State University, Ado-Ekiti", type: "State" },
    { name: "Enugu State University of Science and Technology, Enugu", type: "State" },
    { name: "Gombe State University, Gombe", type: "State" },
    { name: "Ibrahim Badamasi Babangida University, Lapai, Niger State", type: "State" },
    { name: "Ignatius Ajuru University of Education, Port Harcourt, Rivers State", type: "State" },
    { name: "Imo State University, Owerri", type: "State" },
    { name: "Kaduna State University, Kaduna", type: "State" },
    { name: "Kano University of Science and Technology, Wudil", type: "State" },
    { name: "Kebbi State University of Science and Technology, Aliero", type: "State" },
    { name: "Kogi State University, Anyigba", type: "State" },
    { name: "Kwara State University, Malete", type: "State" },
    { name: "Ladoke Akintola University of Technology, Ogbomoso, Oyo State", type: "State" },
    { name: "Lagos State University, Ojo, Lagos State", type: "State" },
    { name: "Nasarawa State University, Keffi", type: "State" },
    { name: "Niger Delta University, Wilberforce Island, Bayelsa State", type: "State" },
    { name: "Northwest University, Kano, Kano State", type: "State" },
    { name: "Olabisi Onabanjo University, Ago-Iwoye, Ogun State", type: "State" },
    { name: "Ondo State University of Medical Sciences, Ondo State", type: "State" },
    { name: "Ondo State University of Science and Technology, Okitipupa", type: "State" },
    { name: "Osun State University, Oshogbo", type: "State" },
    { name: "Plateau State University, Bokkos", type: "State" },
    { name: "Rivers State University, Port Harcourt", type: "State" },
    { name: "Sokoto State University, Sokoto", type: "State" },
    { name: "Tai Solarin University of Education, Ijebu-Ode, Ogun State", type: "State" },
    { name: "Taraba State University, Jalingo", type: "State" },
    { name: "Technical University, Ibadan, Oyo State", type: "State" },
    { name: "Umaru Musa Yar'adua University, Katsina", type: "State" },
    { name: "University of Medical Sciences, Ondo, Ondo State", type: "State" },
    { name: "Yusuf Maitama Sule University, Kano", type: "State" },
    { name: "Zamfara State University, Talata Mafara", type: "State" },
    // Private Universities
    { name: "Achievers University, Owo, Ondo State", type: "Private" },
    { name: "Adeleke University, Ede, Osun State", type: "Private" },
    { name: "Afe Babalola University, Ado-Ekiti, Ekiti State", type: "Private" },
    { name: "African University of Science & Technology, Abuja", type: "Private" },
    { name: "Ajayi Crowther University, Oyo, Oyo State", type: "Private" },
    { name: "Al-Hikmah University, Ilorin, Kwara State", type: "Private" },
    { name: "Al-Qalam University, Katsina, Katsina State", type: "Private" },
    { name: "American University of Nigeria, Yola, Adamawa State", type: "Private" },
    { name: "Anchor University, Ayobo, Lagos State", type: "Private" },
    { name: "Arthur Jarvis University, Akpabuyo, Cross River State", type: "Private" },
    { name: "Atiba University, Oyo, Oyo State", type: "Private" },
    { name: "Augustine University, Ilara, Lagos State", type: "Private" },
    { name: "Babcock University, Ilishan-Remo, Ogun State", type: "Private" },
    { name: "Baze University, Abuja, FCT", type: "Private" },
    { name: "Bells University of Technology, Otta, Ogun State", type: "Private" },
    { name: "Benson Idahosa University, Benin City, Edo State", type: "Private" },
    { name: "Bingham University, Karu, Nasarawa State", type: "Private" },
    { name: "Bowen University, Iwo, Osun State", type: "Private" },
    { name: "Caleb University, Imota, Lagos State", type: "Private" },
    { name: "Caritas University, Enugu, Enugu State", type: "Private" },
    { name: "Chrisland University, Abeokuta, Ogun State", type: "Private" },
    { name: "Christopher University, Mowe, Ogun State", type: "Private" },
    { name: "Clifford University, Owerrinta, Abia State", type: "Private" },
    { name: "Coal City University, Enugu, Enugu State", type: "Private" },
    { name: "Covenant University, Ota, Ogun State", type: "Private" },
    { name: "Crawford University, Igbesa, Ogun State", type: "Private" },
    { name: "Crescent University, Abeokuta, Ogun State", type: "Private" },
    { name: "Edwin Clark University, Kiagbodo, Delta State", type: "Private" },
    { name: "Elizade University, Ilara-Mokin, Ondo State", type: "Private" },
    { name: "Evangel University, Akaeze, Ebonyi State", type: "Private" },
    { name: "Fountain University, Oshogbo, Osun State", type: "Private" },
    { name: "Godfrey Okoye University, Ugwuomu-Nike, Enugu State", type: "Private" },
    { name: "Gregory University, Uturu, Abia State", type: "Private" },
    { name: "Hallmark University, Ijebu-Itele, Ogun State", type: "Private" },
    { name: "Hezekiah University, Umudi, Imo State", type: "Private" },
    { name: "Igbinedion University, Okada, Benin City, Edo State", type: "Private" },
    { name: "Joseph Ayo Babalola University, Ikeji-Arakeji, Osun State", type: "Private" },
    { name: "Kings University, Ode-Omu, Osun State", type: "Private" },
    { name: "Kola Daisi University, Ibadan, Oyo State", type: "Private" },
    { name: "Landmark University, Omu-Aran, Kwara State", type: "Private" },
    { name: "Lead City University, Ibadan, Oyo State", type: "Private" },
    { name: "Madonna University, Okija, Anambra State", type: "Private" },
    { name: "McPherson University, Seriki Sotayo, Ajebo, Ogun State", type: "Private" },
    { name: "Micheal & Cecilia Ibru University, Owhrode, Delta State", type: "Private" },
    { name: "Mountain Top University, Makogi/Oba, Ogun State", type: "Private" },
    { name: "Nigerian British University, Asa, Abia State", type: "Private" },
    { name: "Nile University of Nigeria, Abuja", type: "Private" },
    { name: "Novena University, Ogume, Delta State", type: "Private" },
    { name: "Obong University, Obong Ntak, Akwa Ibom State", type: "Private" },
    { name: "Oduduwa University, Ipetumodu, Osun State", type: "Private" },
    { name: "Pan-Atlantic University, Lagos, Lagos State", type: "Private" },
    { name: "Paul University, Awka, Anambra State", type: "Private" },
    { name: "Precious Cornerstone University, Ibadan, Oyo State", type: "Private" },
    { name: "Redeemer's University, Ede, Osun State", type: "Private" },
    { name: "Renaissance University, Enugu, Enugu State", type: "Private" },
    { name: "Rhema University, Obeama-Asa, Rivers State", type: "Private" },
    { name: "Ritman University, Ikot Ekpene, Akwa Ibom State", type: "Private" },
    { name: "Salerno University, Lokoja, Kogi State", type: "Private" },
    { name: "Samuel Adegboyega University, Ogwa, Edo State", type: "Private" },
    { name: "Skyline University Nigeria, Kano, Kano State", type: "Private" },
    { name: "Southwestern University, Oku Owa, Ogun State", type: "Private" },
    { name: "Summit University, Offa, Kwara State", type: "Private" },
    { name: "Tansian University, Umunya, Anambra State", type: "Private" },
    { name: "University of Mkar, Mkar, Gboko, Benue State", type: "Private" },
    { name: "Veritas University, Abuja, FCT", type: "Private" },
    { name: "Wellspring University, Irhirhi, Benin City, Edo State", type: "Private" },
    { name: "Wesley University of Science & Technology, Ondo, Ondo State", type: "Private" },
    { name: "Western Delta University, Oghara, Delta State", type: "Private" },
    { name: "Al-Ansar University, Maiduguri, Borno State", type: "Private" },
];

export const mockProducts: Product[] = [
  {
    id: 1,
    name: 'HP Spectre x360',
    price: 450000,
    description: 'Slightly used HP Spectre x360, 16GB RAM, 512GB SSD. Perfect for engineering students. Comes with charger and a protective sleeve. Battery health is at 95%.',
    imageUrl: 'https://picsum.photos/seed/laptop1/400/300',
    universityName: 'University of Lagos, Akoka',
    category: 'Electronics',
    condition: 'Used',
    seller: { id: 101, name: 'Ada from Unilag' }
  },
  {
    id: 2,
    name: 'Principles of Economics Textbook',
    price: 5000,
    description: '10th Edition by Mankiw. No markings, like new. Essential for first-year economics. Covered in a plastic wrap since day one.',
    imageUrl: 'https://picsum.photos/seed/book2/400/300',
    universityName: 'University of Ibadan, Ibadan',
    category: 'Books',
    condition: 'New',
    seller: { id: 102, name: 'Tunde from UI' }
  },
  {
    id: 3,
    name: 'Acoustic Guitar',
    price: 35000,
    description: 'Yamaha F310 Acoustic Guitar with bag. Great for beginners. Barely used, strings were recently replaced.',
    imageUrl: 'https://picsum.photos/seed/guitar3/400/300',
    universityName: 'Obafemi Awolowo University, Ile-Ife',
    category: 'Hobbies',
    condition: 'Used',
    seller: { id: 103, name: 'Chioma from OAU' }
  },
  {
    id: 4,
    name: 'Mini Fridge',
    price: 40000,
    description: 'Compact mini fridge, perfect for hostel rooms. Keeps drinks and snacks cool. Energy efficient and quiet.',
    imageUrl: 'https://picsum.photos/seed/fridge4/400/300',
    universityName: 'Ahmadu Bello University, Zaria',
    category: 'Appliances',
    condition: 'Used',
    seller: { id: 104, name: 'Musa from ABU' }
  },
  {
    id: 5,
    name: 'Custom Beaded Necklace',
    price: 3500,
    description: 'Handmade beaded necklace. Can be customized with your name or department color. Made with high-quality, durable beads.',
    imageUrl: 'https://picsum.photos/seed/necklace5/400/300',
    universityName: 'University of Benin, Benin City',
    category: 'Fashion',
    condition: 'New',
    seller: { id: 105, name: 'Efosa from Uniben' }
  },
  {
    id: 6,
    name: 'PlayStation 4 Console',
    price: 120000,
    description: 'PS4 Slim 1TB with two controllers and FIFA 23. Excellent condition, comes in original packaging.',
    imageUrl: 'https://picsum.photos/seed/ps46/400/300',
    universityName: 'Covenant University, Ota',
    category: 'Gaming',
    condition: 'Used',
    seller: { id: 106, name: 'David from CU' }
  },
  {
    id: 7,
    name: 'Complete Art Supplies Set',
    price: 15000,
    description: 'Includes sketchpad, charcoal pencils, acrylic paints, and brushes. For fine arts students. All items are brand new and sealed.',
    imageUrl: 'https://picsum.photos/seed/art7/400/300',
    universityName: 'University of Nigeria, Nsukka',
    category: 'Hobbies',
    condition: 'New',
    seller: { id: 103, name: 'Chioma from OAU' }
  },
  {
    id: 8,
    name: 'Nike Air Force 1 Sneakers',
    price: 25000,
    description: 'White Air Force 1, size 43. Worn a few times, still very clean. Comes with the original box.',
    imageUrl: 'https://picsum.photos/seed/shoes8/400/300',
    universityName: 'Lagos State University, Ojo',
    category: 'Fashion',
    condition: 'Used',
    seller: { id: 101, name: 'Ada from Unilag' }
  },
   {
    id: 9,
    name: 'Samsung Galaxy A52',
    price: 95000,
    description: 'Used Samsung Galaxy A52, 128GB storage. Good battery life and camera. No scratches on the screen.',
    imageUrl: 'https://picsum.photos/seed/phone9/400/300',
    universityName: 'University of Port Harcourt, Port Harcourt',
    category: 'Electronics',
    condition: 'Used',
    seller: { id: 107, name: 'Precious from Uniport' }
  },
  {
    id: 10,
    name: 'Organic Chemistry Study Guide',
    price: 4000,
    description: 'Concise study guide with practice questions for CHEM 201. Unused, no pen or pencil marks.',
    imageUrl: 'https://picsum.photos/seed/book10/400/300',
    universityName: 'Afe Babalola University, Ado-Ekiti',
    category: 'Books',
    condition: 'New',
    seller: { id: 102, name: 'Tunde from UI' }
  },
  {
    id: 11,
    name: 'Portable Blender',
    price: 12000,
    description: 'Rechargeable portable blender for smoothies on the go. Brand new in box, never opened.',
    imageUrl: 'https://picsum.photos/seed/blender11/400/300',
    universityName: 'Babcock University, Ilishan-Remo',
    category: 'Appliances',
    condition: 'New',
    seller: { id: 106, name: 'David from CU' }
  },
  {
    id: 12,
    name: 'Graphic Design Tutoring',
    price: 20000,
    description: 'Offering 4 weeks of beginner-friendly graphic design tutoring. Learn Canva and Figma. Online or in-person sessions available.',
    imageUrl: 'https://picsum.photos/seed/service12/400/300',
    universityName: 'University of Ilorin, Ilorin',
    category: 'Services',
    condition: 'New',
    seller: { id: 101, name: 'Ada from Unilag' }
  }
];
